global using Xunit;   
global using DisprzTraining.Tests.MockData;
global using DisprzTraining.Business;
global using DisprzTraining.Controllers;
global using DisprzTraining.DataAccess;
global using DisprzTraining.Models;
global using Microsoft.AspNetCore.Mvc;
global using Moq;
global using FluentAssertions;